---
shared:
  # (Source: https://hub.docker.com/r/library/buildpack-deps/)
  image: buildpack-deps

# Job definition block
# "main" is a default job that all pipelines have
jobs:
  main:
    requires: [~pr, ~commit]
    # Steps is the list of commands to execute.
    steps:
      - export: export GREETING="Hello, world!"
      - hello: echo $GREETING
      - set-metadata: meta set example.coverage 99.95
  # We define another Job called "second_job". In this Job, we intend on running
  # a different set of commands.
  second_job:
    requires: main
    steps:
      - make_target: make greetings
      - get-metadata: meta get example
      - run_arbitrary_script: ./my_script.sh
